package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"gqlgen-db-viewer/application/model"
	"gqlgen-db-viewer/graphql/generated"
)

// ID is the resolver for the id field.
func (r *orderResolver) ID(ctx context.Context, obj *model.Order) (string, error) {
	return fmt.Sprintf("Order:%d", obj.Iid), nil
}

// Order returns generated.OrderResolver implementation.
func (r *Resolver) Order() generated.OrderResolver { return &orderResolver{r} }

type orderResolver struct{ *Resolver }
